🍰 Some improvements for the UI and logging.
yioyo3/ruminepp pull request #3
Opened 2018-01-10 17:09 UTC by Voknehzyr

Some parts of code may have bugs.

2018-01-10 21:07 UTC, macsmac requested changes
```js
if(localStorage.getItem(m.name + "_enabled") !== "0") {

} else {

}
```

Cleanup & Make a function for spoiler (e.g. `spoiler("#CustomEmoticons", "#spoiler");`)

2018-01-11 17:17 UTC, Voknehzyr commented
> Make a function for spoiler (e.g. spoiler("#CustomEmoticons", "#spoiler");)
?

2018-01-11 17:27 UTC, Voknehzyr commented
I fixed some parts of code.

2018-01-11 21:40 UTC, macsmac commented
я просто хотел продвинутые настройки под другое, поэтому потом наверное в другую ветку мержну

2018-01-11 22:44 UTC, macsmac approved these changes

2018-01-12 09:27 UTC, Voknehzyr commented
Blyad

2018-01-12 09:28 UTC, closed without merging